// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc.proto
#ifndef GRPC_rpc_2eproto__INCLUDED
#define GRPC_rpc_2eproto__INCLUDED

#include "rpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace rpc {

class SampleSvc final {
 public:
  static constexpr char const* service_full_name() {
    return "rpc.SampleSvc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::rpc::RPC1Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC1Response>> AsyncRPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC1Response>>(AsyncRPC_1Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC1Response>> PrepareAsyncRPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC1Response>>(PrepareAsyncRPC_1Raw(context, request, cq));
    }
    virtual ::grpc::Status RPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::rpc::RPC2Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC2Response>> AsyncRPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC2Response>>(AsyncRPC_2Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC2Response>> PrepareAsyncRPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC2Response>>(PrepareAsyncRPC_2Raw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request* request, ::rpc::RPC1Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request* request, ::rpc::RPC1Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request* request, ::rpc::RPC2Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request* request, ::rpc::RPC2Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC1Response>* AsyncRPC_1Raw(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC1Response>* PrepareAsyncRPC_1Raw(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC2Response>* AsyncRPC_2Raw(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rpc::RPC2Response>* PrepareAsyncRPC_2Raw(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::rpc::RPC1Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rpc::RPC1Response>> AsyncRPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rpc::RPC1Response>>(AsyncRPC_1Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rpc::RPC1Response>> PrepareAsyncRPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rpc::RPC1Response>>(PrepareAsyncRPC_1Raw(context, request, cq));
    }
    ::grpc::Status RPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::rpc::RPC2Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rpc::RPC2Response>> AsyncRPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rpc::RPC2Response>>(AsyncRPC_2Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rpc::RPC2Response>> PrepareAsyncRPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rpc::RPC2Response>>(PrepareAsyncRPC_2Raw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request* request, ::rpc::RPC1Response* response, std::function<void(::grpc::Status)>) override;
      void RPC_1(::grpc::ClientContext* context, const ::rpc::RPC1Request* request, ::rpc::RPC1Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request* request, ::rpc::RPC2Response* response, std::function<void(::grpc::Status)>) override;
      void RPC_2(::grpc::ClientContext* context, const ::rpc::RPC2Request* request, ::rpc::RPC2Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rpc::RPC1Response>* AsyncRPC_1Raw(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rpc::RPC1Response>* PrepareAsyncRPC_1Raw(::grpc::ClientContext* context, const ::rpc::RPC1Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rpc::RPC2Response>* AsyncRPC_2Raw(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rpc::RPC2Response>* PrepareAsyncRPC_2Raw(::grpc::ClientContext* context, const ::rpc::RPC2Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RPC_1_;
    const ::grpc::internal::RpcMethod rpcmethod_RPC_2_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RPC_1(::grpc::ServerContext* context, const ::rpc::RPC1Request* request, ::rpc::RPC1Response* response);
    virtual ::grpc::Status RPC_2(::grpc::ServerContext* context, const ::rpc::RPC2Request* request, ::rpc::RPC2Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RPC_1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RPC_1() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RPC_1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_1(::grpc::ServerContext* /*context*/, const ::rpc::RPC1Request* /*request*/, ::rpc::RPC1Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPC_1(::grpc::ServerContext* context, ::rpc::RPC1Request* request, ::grpc::ServerAsyncResponseWriter< ::rpc::RPC1Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RPC_2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RPC_2() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RPC_2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_2(::grpc::ServerContext* /*context*/, const ::rpc::RPC2Request* /*request*/, ::rpc::RPC2Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPC_2(::grpc::ServerContext* context, ::rpc::RPC2Request* request, ::grpc::ServerAsyncResponseWriter< ::rpc::RPC2Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RPC_1<WithAsyncMethod_RPC_2<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RPC_1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RPC_1() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rpc::RPC1Request, ::rpc::RPC1Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rpc::RPC1Request* request, ::rpc::RPC1Response* response) { return this->RPC_1(context, request, response); }));}
    void SetMessageAllocatorFor_RPC_1(
        ::grpc::MessageAllocator< ::rpc::RPC1Request, ::rpc::RPC1Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rpc::RPC1Request, ::rpc::RPC1Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RPC_1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_1(::grpc::ServerContext* /*context*/, const ::rpc::RPC1Request* /*request*/, ::rpc::RPC1Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RPC_1(
      ::grpc::CallbackServerContext* /*context*/, const ::rpc::RPC1Request* /*request*/, ::rpc::RPC1Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RPC_2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RPC_2() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::rpc::RPC2Request, ::rpc::RPC2Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rpc::RPC2Request* request, ::rpc::RPC2Response* response) { return this->RPC_2(context, request, response); }));}
    void SetMessageAllocatorFor_RPC_2(
        ::grpc::MessageAllocator< ::rpc::RPC2Request, ::rpc::RPC2Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rpc::RPC2Request, ::rpc::RPC2Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RPC_2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_2(::grpc::ServerContext* /*context*/, const ::rpc::RPC2Request* /*request*/, ::rpc::RPC2Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RPC_2(
      ::grpc::CallbackServerContext* /*context*/, const ::rpc::RPC2Request* /*request*/, ::rpc::RPC2Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RPC_1<WithCallbackMethod_RPC_2<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RPC_1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RPC_1() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RPC_1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_1(::grpc::ServerContext* /*context*/, const ::rpc::RPC1Request* /*request*/, ::rpc::RPC1Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RPC_2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RPC_2() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RPC_2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_2(::grpc::ServerContext* /*context*/, const ::rpc::RPC2Request* /*request*/, ::rpc::RPC2Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RPC_1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RPC_1() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RPC_1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_1(::grpc::ServerContext* /*context*/, const ::rpc::RPC1Request* /*request*/, ::rpc::RPC1Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPC_1(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RPC_2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RPC_2() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RPC_2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_2(::grpc::ServerContext* /*context*/, const ::rpc::RPC2Request* /*request*/, ::rpc::RPC2Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPC_2(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RPC_1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RPC_1() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RPC_1(context, request, response); }));
    }
    ~WithRawCallbackMethod_RPC_1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_1(::grpc::ServerContext* /*context*/, const ::rpc::RPC1Request* /*request*/, ::rpc::RPC1Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RPC_1(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RPC_2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RPC_2() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RPC_2(context, request, response); }));
    }
    ~WithRawCallbackMethod_RPC_2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_2(::grpc::ServerContext* /*context*/, const ::rpc::RPC2Request* /*request*/, ::rpc::RPC2Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RPC_2(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RPC_1 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RPC_1() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rpc::RPC1Request, ::rpc::RPC1Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rpc::RPC1Request, ::rpc::RPC1Response>* streamer) {
                       return this->StreamedRPC_1(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RPC_1() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RPC_1(::grpc::ServerContext* /*context*/, const ::rpc::RPC1Request* /*request*/, ::rpc::RPC1Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRPC_1(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rpc::RPC1Request,::rpc::RPC1Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RPC_2 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RPC_2() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rpc::RPC2Request, ::rpc::RPC2Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rpc::RPC2Request, ::rpc::RPC2Response>* streamer) {
                       return this->StreamedRPC_2(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RPC_2() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RPC_2(::grpc::ServerContext* /*context*/, const ::rpc::RPC2Request* /*request*/, ::rpc::RPC2Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRPC_2(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rpc::RPC2Request,::rpc::RPC2Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RPC_1<WithStreamedUnaryMethod_RPC_2<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RPC_1<WithStreamedUnaryMethod_RPC_2<Service > > StreamedService;
};

}  // namespace rpc


#endif  // GRPC_rpc_2eproto__INCLUDED
